site_name: Subathon Manager
site_url: https://docs.subathonmanager.app/
site_author: WolfwithSword
site_description: SubathonManager - a feature-rich subathon app for streamers
repo_name: WolfwithSword/SubathonManager
repo_url: https://github.com/WolfwithSword/SubathonManager
edit_uri: ""

docs_dir: wiki

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - announce.dismiss

  icon:
    repo: fontawesome/brands/github

  custom_dir: wiki/overrides

extra:
  version:
    provider: mike
    default: nightly
  docs_version: !ENV [DOCS_VERSION, "dev"] #ignore error
  noindex: !ENV [NOINDEX, false]
  docs_canonical: !ENV [DOCS_CANONICAL, false]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WolfwithSword/SubathonManager
    - icon: fontawesome/brands/discord
      link: https://discord.gg/qp4Te3bQTk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_WolfwithSword
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/wolfwithsword
  meta:
    - name: og:site_name
      content: "SubathonManager Docs"
    - name: og:image
      content: "https://assets.subathonmanager.app/docs/icon.png"
    - property: og:type
      content: website
    - name: twitter:card
      content: "summary"

extra_css:
  - assets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css

extra_javascript:
  - https://viewer.diagrams.net/js/viewer-static.min.js
  - assets/javascripts/drawio-reload.js
  - assets/javascripts/marketplace.js

plugins:
  - search
  - macros
  - glightbox
  - awesome-nav
  - tags
  - drawio:
      tooltips: true 
      border: 5
      darkmode: true
      edit: false
      highlight: "#0000FF"
      lightbox: true
      toolbar:
        pages: true
        tags: true
        zoom: true
        layers: true
        lightbox: true
        position: "top"
        no_hide: true
        show_title: false
  - mike:
      alias_type: symlink
      redirect_template: wiki/overrides/redirect.html
      deploy_prefix: ''
      canonical_version: latest
      version_selector: true
      css_dir: assets
      javascript_dir: assets

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji: # ignore errors
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      title: On this page
